"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, Bold, Check, ChevronDown, Clock3, Cloud, CloudAlert, Eye, FileText, History, ImageIcon, Italic, Link2, List, Loader2, RefreshCcw, Rocket, Save, SearchCheck, Smartphone, Upload } from "lucide-react";
import { finalizeServiceImageUpload, prepareServiceImageUpload, publishService, restoreServiceRevision, saveServiceDraft, unpublishService } from "@/app/dashboard/services/actions";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import type { ServiceContentData, ServiceDraftData, ServiceSeoData } from "@/lib/cms/services/schema";
import type { CmsServiceEditorData } from "@/lib/cms/services/types";
import { ServicePreview } from "./service-preview";

type Tab = "content" | "seo" | "history";
type SaveStatus = "saved" | "dirty" | "saving" | "error";
type Props = { service: CmsServiceEditorData; canEdit: boolean; canPublish: boolean; canUpload: boolean };
const signature = (draft: ServiceDraftData) => JSON.stringify(draft);
const formatDate = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const eventLabel = (event: CmsServiceEditorData["revisions"][number]["event"]) => ({ draft_saved: "Draft saved", published: "Published", unpublished: "Moved to draft", archived: "Archived", restored: "Restored" })[event];
async function sha256(file: File) { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function imageDimensions(file: File) { try { const bitmap = await createImageBitmap(file); const result = { width: bitmap.width, height: bitmap.height }; bitmap.close(); return result; } catch { return { width: null, height: null }; } }

export function ServiceEditor({ service, canEdit, canPublish, canUpload }: Props) {
  const router = useRouter();
  const [draft, setDraft] = useState<ServiceDraftData>({ content: service.content, seo: service.seo });
  const [tab, setTab] = useState<Tab>("content");
  const [status, setStatus] = useState<SaveStatus>("saved");
  const [notice, setNotice] = useState<string | null>(null);
  const [published, setPublished] = useState(service.status === "published");
  const [busy, setBusy] = useState<"publish" | "unpublish" | "version" | "restore" | "upload" | null>(null);
  const [mobilePreview, setMobilePreview] = useState(false);
  const [savedSignature, setSavedSignature] = useState(() => signature(draft));
  const lockRef = useRef(service.lockVersion); const draftRef = useRef(draft); const savingRef = useRef(false); const descriptionRef = useRef<HTMLTextAreaElement>(null);
  const dirty = signature(draft) !== savedSignature;
  useEffect(() => { draftRef.current = draft; }, [draft]);
  useEffect(() => {
    if (!dirty) return;
    const unload = (event: BeforeUnloadEvent) => event.preventDefault();
    const navigate = (event: MouseEvent) => { const target = event.target; if (!(target instanceof Element)) return; const anchor = target.closest("a"); if (anchor && anchor.target !== "_blank" && anchor.href !== window.location.href && !window.confirm("You have unsaved changes. Leave this page?")) { event.preventDefault(); event.stopPropagation(); } };
    window.addEventListener("beforeunload", unload); document.addEventListener("click", navigate, true);
    return () => { window.removeEventListener("beforeunload", unload); document.removeEventListener("click", navigate, true); };
  }, [dirty]);

  const performSave = useCallback(async (version: boolean) => {
    if (!canEdit || savingRef.current) return false;
    const payload = draftRef.current; const saved = signature(payload); savingRef.current = true; setStatus("saving"); setNotice(null);
    const result = await saveServiceDraft(service.id, lockRef.current, payload, version); savingRef.current = false;
    if (!result.ok) { setStatus("error"); setNotice(result.message); return false; }
    lockRef.current = result.lockVersion; setSavedSignature(saved); setStatus(signature(draftRef.current) === saved ? "saved" : "dirty"); if (result.message) setNotice(result.message); if (version) router.refresh(); return true;
  }, [canEdit, router, service.id]);
  function updateContent<K extends keyof ServiceContentData>(key: K, value: ServiceContentData[K]) { setDraft((current) => ({ ...current, content: { ...current.content, [key]: value } })); setStatus("dirty"); setNotice(null); }
  function updateSeo<K extends keyof ServiceSeoData>(key: K, value: ServiceSeoData[K]) { setDraft((current) => ({ ...current, seo: { ...current.seo, [key]: value } })); setStatus("dirty"); setNotice(null); }
  function applyMarkup(prefix: string, suffix = prefix, fallback = "text") { const textarea = descriptionRef.current; if (!textarea) return; const start = textarea.selectionStart; const end = textarea.selectionEnd; const selected = draft.content.description.slice(start, end) || fallback; updateContent("description", `${draft.content.description.slice(0, start)}${prefix}${selected}${suffix}${draft.content.description.slice(end)}`); requestAnimationFrame(() => { textarea.focus(); textarea.setSelectionRange(start + prefix.length, start + prefix.length + selected.length); }); }

  async function handlePublish() { if (!window.confirm("Publish this service to the live website?")) return; setBusy("publish"); const payload = draftRef.current; const result = await publishService(service.id, lockRef.current, payload); setBusy(null); if (!result.ok) { setStatus("error"); setNotice(result.message); return; } lockRef.current = result.lockVersion; setSavedSignature(signature(payload)); setStatus("saved"); setPublished(true); setNotice(result.message ?? "Service published."); router.refresh(); }
  async function handleUnpublish() { if (!window.confirm("Move this service to draft? It will disappear from the public services grid.")) return; setBusy("unpublish"); const result = await unpublishService(service.id, lockRef.current); setBusy(null); if (!result.ok) { setNotice(result.message); return; } lockRef.current = result.lockVersion; setPublished(false); setNotice(result.message ?? "Service moved to draft."); router.refresh(); }
  async function handleRestore(id: string, version: number) { if (!window.confirm(`Restore version ${version} as the current draft?`)) return; setBusy("restore"); const result = await restoreServiceRevision(service.id, id, lockRef.current); setBusy(null); if (!result.ok || !result.draft) { setNotice(result.message || "The version is invalid."); return; } lockRef.current = result.lockVersion; draftRef.current = result.draft; setDraft(result.draft); setSavedSignature(signature(result.draft)); setStatus("saved"); setNotice(result.message ?? "Version restored."); router.refresh(); }
  async function handleUpload(file?: File) { if (!file) return; setBusy("upload"); setNotice(null); try { const [checksum, dimensions] = await Promise.all([sha256(file), imageDimensions(file)]); const prepared = await prepareServiceImageUpload({ serviceId: service.id, fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp" | "image/avif", byteSize: file.size, checksum }); if (!prepared.ok) throw new Error(prepared.message); let uploaded: { assetId: string; url: string }; if (prepared.existing) uploaded = prepared; else { const supabase = createSupabaseBrowserClient(); const { error } = await supabase.storage.from("site-media").uploadToSignedUrl(prepared.path, prepared.token, file, { contentType: file.type }); if (error) throw error; const result = await finalizeServiceImageUpload({ serviceId: service.id, fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp" | "image/avif", byteSize: file.size, checksum, storagePath: prepared.path, width: dimensions.width, height: dimensions.height, altText: draftRef.current.content.image.alt }); if (!result.ok) throw new Error(result.message); uploaded = result; } updateContent("image", { ...draftRef.current.content.image, assetId: uploaded.assetId, url: uploaded.url }); setNotice("Image uploaded. Autosave will attach it to this draft."); } catch (error) { setNotice(error instanceof Error ? error.message : "The image could not be uploaded."); } finally { setBusy(null); } }

  const statusInfo = {
    saved: { icon: Check, label: "All changes saved", className: "text-emerald-700" },
    dirty: { icon: Cloud, label: "Unsaved changes", className: "text-amber-700" },
    saving: { icon: Loader2, label: "Saving…", className: "text-blue-700" },
    error: { icon: CloudAlert, label: "Save failed", className: "text-red-700" },
  }[status];
  const StatusIcon = statusInfo.icon;
  return (
    <div className="space-y-5">
      <section className="rounded-[1.5rem] border border-slate-200/80 bg-white p-4 shadow-sm sm:p-5">
          <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 items-start gap-3"><Link href="/dashboard/services" aria-label="Back to services" className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><ArrowLeft className="h-4 w-4" /></Link><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl! font-bold text-slate-900">{draft.content.title}</h2><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider ${published ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{published ? "Published" : "Draft"}</span></div><div className="mt-1 flex flex-wrap items-center gap-3"><span className="font-mono text-xs text-slate-500">{draft.content.slug}</span><span className={`inline-flex items-center gap-1.5 text-[10px] font-bold ${statusInfo.className}`} aria-live="polite"><StatusIcon className={`h-3.5 w-3.5 ${status === "saving" ? "animate-spin" : ""}`} />{statusInfo.label}</span></div></div></div>
          <div className="flex flex-wrap gap-2"><button type="button" onClick={() => setMobilePreview((value) => !value)} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3.5 text-xs font-bold text-slate-600 xl:hidden"><Eye className="h-4 w-4" />Live preview</button>{canEdit && <button type="button" disabled={Boolean(busy)} onClick={async () => { setBusy("version"); await performSave(true); setBusy(null); }} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3.5 text-xs font-bold text-slate-700 disabled:opacity-50"><Save className="h-4 w-4" />Save version</button>}{canPublish && published && <button type="button" disabled={Boolean(busy)} onClick={handleUnpublish} className="inline-flex h-10 items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3.5 text-xs font-bold text-amber-800"><ChevronDown className="h-4 w-4" />Move to draft</button>}{canPublish && <button type="button" disabled={Boolean(busy)} onClick={handlePublish} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#157670] px-4 text-xs font-bold text-white"><Rocket className="h-4 w-4" />{published ? "Publish updates" : "Publish"}</button>}</div></div>
        {notice && <p role="status" className={`mt-4 flex items-start gap-2 rounded-xl px-3.5 py-3 text-xs ${status === "error" ? "bg-red-50 text-red-700" : "bg-slate-50 text-slate-700"}`}>{status === "error" && <AlertTriangle className="h-4 w-4 shrink-0" />}{notice}</p>}
      </section>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(390px,.78fr)]">
        <section className="min-w-0 overflow-hidden rounded-[1.5rem] border border-slate-200/80 bg-white shadow-sm"><div className="flex overflow-x-auto border-b border-slate-200 px-2 sm:px-4" role="tablist">{([["content", FileText, "Content"], ["seo", SearchCheck, "SEO"], ["history", History, "History"]] as const).map(([key, Icon, label]) => <button key={key} type="button" role="tab" aria-selected={tab === key} onClick={() => setTab(key)} className={`flex h-14 items-center gap-2 border-b-2 px-4 text-xs font-bold ${tab === key ? "border-[#157670] text-[#157670]" : "border-transparent text-slate-500"}`}><Icon className="h-4 w-4" />{label}</button>)}</div>
          <div className="p-4 sm:p-6">
            {tab === "content" && <fieldset disabled={!canEdit} className="space-y-5 disabled:opacity-70"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-700">Title<input value={draft.content.title} onChange={(e) => updateContent("title", e.target.value)} maxLength={120} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm font-normal outline-none focus:border-[#157670]" /></label><label className="text-xs font-bold text-slate-700">Slug<input value={draft.content.slug} onChange={(e) => updateContent("slug", e.target.value.toLowerCase().replace(/\s+/g, "-"))} maxLength={100} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3.5 font-mono text-sm font-normal outline-none focus:border-[#157670]" /></label></div>
              <div><label className="text-xs font-bold text-slate-700">Rich description</label><div className="mt-2 overflow-hidden rounded-xl border border-slate-200"><div className="flex gap-1 border-b border-slate-200 bg-slate-50 p-2"><button type="button" onClick={() => applyMarkup("**")} aria-label="Bold" className="rounded-lg p-2 hover:bg-white"><Bold className="h-4 w-4" /></button><button type="button" onClick={() => applyMarkup("_")} aria-label="Italic" className="rounded-lg p-2 hover:bg-white"><Italic className="h-4 w-4" /></button><button type="button" onClick={() => applyMarkup("[", "](https://)", "link text")} aria-label="Link" className="rounded-lg p-2 hover:bg-white"><Link2 className="h-4 w-4" /></button><button type="button" onClick={() => applyMarkup("\n- ", "", "list item")} aria-label="List" className="rounded-lg p-2 hover:bg-white"><List className="h-4 w-4" /></button></div><textarea ref={descriptionRef} value={draft.content.description} onChange={(e) => updateContent("description", e.target.value)} rows={9} maxLength={5000} className="w-full resize-y px-3.5 py-3 text-sm leading-6 outline-none" /></div><p className="mt-1.5 text-right text-[10px] text-slate-400">{draft.content.description.length}/5000</p></div>
              <div className="grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold text-slate-700 sm:col-span-1">Eyebrow<input value={draft.content.eyebrow} onChange={(e) => updateContent("eyebrow", e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-700">Icon key<input value={draft.content.iconKey} onChange={(e) => updateContent("iconKey", e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-700">Display order<input type="number" min={0} max={9999} value={draft.content.sortOrder} onChange={(e) => updateContent("sortOrder", Number(e.target.value))} className="mt-2 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal" /></label></div>
              <div className="border-t border-slate-100 pt-6"><div className="flex items-center justify-between"><div><p className="text-[10px]! font-bold uppercase tracking-wider text-[#157670]">Service image</p><h3 className="mt-1 text-lg! font-bold text-slate-900">Reusable media asset</h3></div><ImageIcon className="h-5 w-5 text-slate-300" /></div><div className="mt-4 overflow-hidden rounded-2xl border border-slate-200"><div className="relative aspect-[16/7] bg-slate-100 bg-cover bg-center" style={{ backgroundImage: `url(${draft.content.image.url || "/images/services-hero.jpg"})` }}>{canUpload && <label className="absolute inset-0 flex cursor-pointer items-center justify-center bg-slate-950/20"><span className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-slate-800"><Upload className="h-4 w-4" />{busy === "upload" ? "Uploading…" : "Replace image"}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={(e) => void handleUpload(e.target.files?.[0])} /></label>}</div><div className="p-4"><label className="text-xs font-bold text-slate-700">Alternative text<input value={draft.content.image.alt} onChange={(e) => updateContent("image", { ...draft.content.image, alt: e.target.value })} className="mt-2 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal" /></label></div></div></div>
            </fieldset>}
            {tab === "seo" && <fieldset disabled={!canEdit} className="space-y-5 disabled:opacity-70"><div><p className="text-[10px]! font-bold uppercase tracking-wider text-[#157670]">Search metadata</p><h3 className="mt-1 text-lg! font-bold text-slate-900">SEO and social sharing</h3></div><label className="block text-xs font-bold text-slate-700">SEO title<input value={draft.seo.title} onChange={(e) => updateSeo("title", e.target.value)} maxLength={70} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm font-normal" /></label><label className="block text-xs font-bold text-slate-700">Meta description<textarea value={draft.seo.description} onChange={(e) => updateSeo("description", e.target.value)} maxLength={170} rows={4} className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm font-normal" /></label><label className="block text-xs font-bold text-slate-700">Canonical path<input value={draft.seo.canonicalPath} onChange={(e) => updateSeo("canonicalPath", e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3.5 font-mono text-sm font-normal" /></label><label className="block text-xs font-bold text-slate-700">Social image URL<input value={draft.seo.ogImage} onChange={(e) => updateSeo("ogImage", e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm font-normal" /></label><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs! font-semibold text-blue-700">{draft.seo.title || draft.content.title}</p><p className="mt-1 text-[10px]! text-emerald-700">https://flashtour.travel{draft.seo.canonicalPath}</p><p className="mt-2 text-xs! leading-5! text-slate-600">{draft.seo.description || draft.content.description.slice(0, 170)}</p></div></fieldset>}
            {tab === "history" && <div><div><p className="text-[10px]! font-bold uppercase tracking-wider text-[#157670]">Version history</p><h3 className="mt-1 text-lg! font-bold text-slate-900">Recent versions</h3><p className="mt-1 text-xs! text-slate-500">Restoring changes only the draft until you publish.</p></div><div className="mt-5 space-y-3">{service.revisions.map((revision) => <article key={revision.id} className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4"><Clock3 className="mt-1 h-4 w-4 text-slate-400" /><div className="min-w-0 flex-1"><p className="text-xs! font-bold text-slate-800">Version {revision.version} · {eventLabel(revision.event)}</p><p className="mt-1 text-[10px]! text-slate-500">{formatDate(revision.createdAt)}{revision.authorName ? ` · ${revision.authorName}` : ""}</p></div>{canEdit && <button type="button" onClick={() => handleRestore(revision.id, revision.version)} disabled={Boolean(busy)} className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 px-3 text-[10px] font-bold text-slate-600"><RefreshCcw className="h-3.5 w-3.5" />Restore</button>}</article>)}</div></div>}
          </div>
        </section>
        <aside className={`${mobilePreview ? "block" : "hidden"} min-w-0 xl:block`}><div className="space-y-3 xl:sticky xl:top-0"><div className="flex items-center justify-between px-1"><span className="flex items-center gap-2 text-xs font-bold text-slate-700"><Smartphone className="h-4 w-4 text-[#157670]" />Live draft preview</span><span className="text-[10px] text-slate-400">Updates instantly</span></div><ServicePreview content={draft.content} published={published} /></div></aside>
      </div>
    </div>
  );
}
