"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireCmsPermission } from "@/lib/auth/session";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { draftSchema, managedContentTypeSchema, validateGalleryUrls, type ManagedContentType } from "@/lib/cms/collections/schema";
import type { MutationResult } from "@/lib/cms/collections/types";
import type { Json } from "@/types/database.generated";

const mutationSchema = z.object({ id: z.uuid(), lockVersion: z.number().int().positive(), type: managedContentTypeSchema, draft: draftSchema });
const createSchema = z.object({ type: managedContentTypeSchema, draft: draftSchema });
const routes = ["/dashboard/hospitality", "/dashboard/destinations", "/dashboard/cruises", "/dashboard/brands"];
const result = (ok: boolean, message: string, extra: Partial<Extract<MutationResult, { ok: true }>> = {}): MutationResult => ok ? { ok: true, message, ...extra } : { ok: false, message };
const json = (value: unknown) => value as Json;
function errorResult(error: { code?: string; message: string }): MutationResult { if (error.code === "23505") return { ok: false, message: "Another item already uses this slug." }; return error.code === "40001" ? { ok: false, conflict: true, message: "This item changed in another session. Reload it before continuing." } : { ok: false, message: error.message }; }
function relationFor(type: ManagedContentType) { return type === "destination_place" ? { parent: "destination", relation: "contains_place" } : type === "destination_attraction" ? { parent: "destination_place", relation: "contains_attraction" } : null; }
async function validateParent(type: ManagedContentType, parentId: string | null) { const expected = relationFor(type); if (!expected) return null; if (!parentId) return "Choose a parent before saving."; const s = await createSupabaseServerClient(); const { data } = await s.from("content_entries").select("id,content_type,status").eq("id", parentId).maybeSingle(); return !data || data.status === "archived" || data.content_type !== expected.parent ? "The selected parent is not valid for this item." : null; }
async function validateHospitality(type: ManagedContentType, categoryId: string | null, galleryError: string | null) {
  if (galleryError) return galleryError;
  if (type !== "hospitality") return null;
  if (!categoryId) return "Choose a hospitality category before saving.";
  const s = await createSupabaseServerClient();
  const { data, error } = await s.from("hospitality_categories").select("id").eq("id", categoryId).eq("is_active", true).maybeSingle();
  return error || !data ? "The selected hospitality category is not available." : null;
}
function dataFor(type: ManagedContentType, content: z.infer<typeof draftSchema>["content"]) { return { title: content.title, name: content.title, slug: content.slug, shortDescription: content.shortDescription, summary: content.shortDescription, fullDescription: content.fullDescription, country: content.country, region: content.region, location: content.location, categoryId: content.categoryId, rooms: content.rooms, cabins: content.cabins, suites: content.suites, facilities: content.facilities, diningOptions: content.diningOptions, accessibility: content.accessibility, gallery: content.gallery, displayOrder: content.displayOrder, sortOrder: content.displayOrder, isActive: content.isActive, showcaseRegion: content.showcaseRegion, showcaseIcon: content.showcaseIcon, kind: type === "destination" ? "country" : type === "destination_place" ? "place" : type === "destination_attraction" ? "attraction" : "hospitality" }; }
async function replaceParent(s: Awaited<ReturnType<typeof createSupabaseServerClient>>, id: string, type: ManagedContentType, parentId: string | null) { const expected = relationFor(type); if (!expected) return null; const invalid = await validateParent(type, parentId); if (invalid) return invalid; const { error: removeError } = await s.from("content_relations").delete().eq("target_id", id).eq("relation_type", expected.relation); if (removeError) return removeError.message; const { error } = await s.from("content_relations").insert({ source_id: parentId!, target_id: id, relation_type: expected.relation, sort_order: 0 }); return error?.message ?? null; }
async function addRevision(s: Awaited<ReturnType<typeof createSupabaseServerClient>>, type: ManagedContentType, id: string, content: unknown, seo: unknown, event: "draft_saved" | "published" | "unpublished" | "archived" | "restored", createdBy: string) { const { data } = await s.from("content_revisions").select("version").eq("resource_type", type).eq("resource_id", id).order("version", { ascending: false }).limit(1); return s.from("content_revisions").insert({ resource_type: type, resource_id: id, version: (data?.[0]?.version ?? 0) + 1, snapshot: json({ content, seo }), event, created_by: createdBy }); }
function revalidate(id?: string) { for (const route of routes) revalidatePath(route); if (id) { revalidatePath(`/dashboard/hospitality/${id}`); revalidatePath(`/dashboard/destinations/${id}`); revalidatePath(`/dashboard/cruises/${id}`); revalidatePath(`/dashboard/brands/${id}`); } }

export async function createCollectionItem(input: unknown): Promise<MutationResult> {
  const user = await requireCmsPermission("content.create"); await requireCmsPermission("seo.edit"); const parsed = createSchema.safeParse(input); if (!parsed.success) return { ok: false, message: "Check the required fields.", fieldErrors: parsed.error.flatten().fieldErrors };
  const parentError = await validateParent(parsed.data.type, parsed.data.draft.parentId); if (parentError) return result(false, parentError); const hospitalityError = await validateHospitality(parsed.data.type, parsed.data.draft.content.categoryId, validateGalleryUrls(parsed.data.draft.content)); if (hospitalityError) return result(false, hospitalityError); const s = await createSupabaseServerClient(); const data = dataFor(parsed.data.type, parsed.data.draft.content);
  const { data: existing } = await s.from("content_entries").select("id").eq("content_type", parsed.data.type).eq("locale", "en").eq("slug", data.slug).maybeSingle(); if (existing) return result(false, "Another item already uses this slug.");
  const { data: entry, error } = await s.from("content_entries").insert({ content_type: parsed.data.type, slug: data.slug, title: data.title, locale: "en", status: "draft", sort_order: data.sortOrder, is_active: data.isActive, draft_data: json(data), created_by: user.id, updated_by: user.id }).select("id,lock_version,updated_at").single(); if (error) return errorResult(error);
  const { error: seoError } = await s.from("seo_entries").insert({ content_entry_id: entry.id, locale: "en", draft_data: json(parsed.data.draft.seo), created_by: user.id, updated_by: user.id }); if (seoError) return errorResult(seoError);
  const relationError = await replaceParent(s, entry.id, parsed.data.type, parsed.data.draft.parentId); if (relationError) return result(false, relationError); const { error: revisionError } = await addRevision(s, parsed.data.type, entry.id, data, parsed.data.draft.seo, "draft_saved", user.id); if (revisionError) return errorResult(revisionError); revalidate(entry.id); return result(true, "Draft created.", { id: entry.id, lockVersion: entry.lock_version, updatedAt: entry.updated_at });
}

export async function saveCollectionDraft(input: unknown, createRevision = false): Promise<MutationResult> {
  const user = await requireCmsPermission("content.edit"); await requireCmsPermission("seo.edit"); const parsed = mutationSchema.safeParse(input); if (!parsed.success) return { ok: false, message: "Check the content fields.", fieldErrors: parsed.error.flatten().fieldErrors };
  const parentError = await validateParent(parsed.data.type, parsed.data.draft.parentId); if (parentError) return result(false, parentError); const hospitalityError = await validateHospitality(parsed.data.type, parsed.data.draft.content.categoryId, validateGalleryUrls(parsed.data.draft.content)); if (hospitalityError) return result(false, hospitalityError); const s = await createSupabaseServerClient(); const { data: current, error: currentError } = await s.from("content_entries").select("status").eq("id", parsed.data.id).eq("content_type", parsed.data.type).maybeSingle(); if (currentError || !current) return result(false, "The requested item was not found."); const data = dataFor(parsed.data.type, parsed.data.draft.content);
  const { data: duplicate } = await s.from("content_entries").select("id").eq("content_type", parsed.data.type).eq("locale", "en").eq("slug", data.slug).neq("id", parsed.data.id).maybeSingle(); if (duplicate) return result(false, "Another item already uses this slug.");
  const update = current.status === "published" ? { draft_data: json(data), is_active: data.isActive, updated_by: user.id } : { draft_data: json(data), title: data.title, slug: data.slug, sort_order: data.sortOrder, is_active: data.isActive, updated_by: user.id };
  const { data: saved, error } = await s.from("content_entries").update(update).eq("id", parsed.data.id).eq("lock_version", parsed.data.lockVersion).select("lock_version,updated_at").maybeSingle(); if (error) return errorResult(error); if (!saved) return { ok: false, conflict: true, message: "This item changed in another session. Reload it before continuing." };
  const { error: seoError } = await s.from("seo_entries").update({ draft_data: json(parsed.data.draft.seo), updated_by: user.id }).eq("content_entry_id", parsed.data.id).eq("locale", "en"); if (seoError) return errorResult(seoError); const relationError = await replaceParent(s, parsed.data.id, parsed.data.type, parsed.data.draft.parentId); if (relationError) return result(false, relationError); if (createRevision) { const { error: revisionError } = await addRevision(s, parsed.data.type, parsed.data.id, data, parsed.data.draft.seo, "draft_saved", user.id); if (revisionError) return errorResult(revisionError); } revalidate(parsed.data.id); return result(true, createRevision ? "Draft and revision saved." : "Draft saved.", { lockVersion: saved.lock_version, updatedAt: saved.updated_at });
}

export async function publishCollectionItem(input: unknown): Promise<MutationResult> {
  const user = await requireCmsPermission("content.publish"); await requireCmsPermission("seo.publish"); const parsed = mutationSchema.safeParse(input); if (!parsed.success) return result(false, "Check the content fields."); const parentError = await validateParent(parsed.data.type, parsed.data.draft.parentId); if (parentError) return result(false, parentError); const s = await createSupabaseServerClient(); const data = dataFor(parsed.data.type, parsed.data.draft.content);
  const hospitalityError = await validateHospitality(parsed.data.type, parsed.data.draft.content.categoryId, validateGalleryUrls(parsed.data.draft.content)); if (hospitalityError) return result(false, hospitalityError);
  const { data: saved, error } = await s.from("content_entries").update({ title: data.title, slug: data.slug, sort_order: data.sortOrder, draft_data: json(data), published_data: json(data), status: "published", published_at: new Date().toISOString(), archived_at: null, is_active: data.isActive, updated_by: user.id }).eq("id", parsed.data.id).eq("content_type", parsed.data.type).eq("lock_version", parsed.data.lockVersion).select("lock_version,updated_at").maybeSingle(); if (error) return errorResult(error); if (!saved) return { ok: false, conflict: true, message: "This item changed in another session. Reload it before publishing." }; const { error: seoError } = await s.from("seo_entries").update({ draft_data: json(parsed.data.draft.seo), published_data: json(parsed.data.draft.seo), published_at: new Date().toISOString(), updated_by: user.id }).eq("content_entry_id", parsed.data.id); if (seoError) return errorResult(seoError); const { error: revisionError } = await addRevision(s, parsed.data.type, parsed.data.id, data, parsed.data.draft.seo, "published", user.id); if (revisionError) return errorResult(revisionError); revalidate(parsed.data.id); return result(true, "Published.", { lockVersion: saved.lock_version, updatedAt: saved.updated_at });
}

export async function archiveCollectionItem(id: string, type: ManagedContentType, lockVersion: number): Promise<MutationResult> { const user = await requireCmsPermission("content.archive"); const valid = z.uuid().safeParse(id); if (!valid.success) return result(false, "Invalid item."); const s = await createSupabaseServerClient(); const { count } = await s.from("content_relations").select("*", { count: "exact", head: true }).eq("source_id", id); if (count) return result(false, "This item has child content. Archive or move its children first."); const { data: saved, error } = await s.from("content_entries").update({ status: "archived", archived_at: new Date().toISOString(), published_data: null, published_at: null, updated_by: user.id }).eq("id", id).eq("content_type", type).eq("lock_version", lockVersion).select("lock_version,updated_at,draft_data").maybeSingle(); if (error) return errorResult(error); if (!saved) return { ok: false, conflict: true, message: "This item changed in another session." }; await s.from("seo_entries").update({ published_data: null, published_at: null, updated_by: user.id }).eq("content_entry_id", id); await addRevision(s, type, id, saved.draft_data, {}, "archived", user.id); revalidate(id); return result(true, "Archived.", { lockVersion: saved.lock_version, updatedAt: saved.updated_at }); }

export async function restoreCollectionRevision(id: string, type: ManagedContentType, revisionId: string, lockVersion: number): Promise<MutationResult> { const user = await requireCmsPermission("content.edit"); await requireCmsPermission("seo.edit"); const s = await createSupabaseServerClient(); const { data: revision } = await s.from("content_revisions").select("snapshot").eq("id", revisionId).eq("resource_id", id).eq("resource_type", type).maybeSingle(); if (!revision || !revision.snapshot || typeof revision.snapshot !== "object") return result(false, "The revision was not found."); const snapshot = revision.snapshot as { content?: Json; seo?: Json }; const { data: saved, error } = await s.from("content_entries").update({ draft_data: snapshot.content ?? {}, updated_by: user.id }).eq("id", id).eq("lock_version", lockVersion).select("lock_version,updated_at").maybeSingle(); if (error) return errorResult(error); if (!saved) return { ok: false, conflict: true, message: "This item changed in another session." }; await s.from("seo_entries").update({ draft_data: snapshot.seo ?? {}, updated_by: user.id }).eq("content_entry_id", id); await addRevision(s, type, id, snapshot.content ?? {}, snapshot.seo ?? {}, "restored", user.id); revalidate(id); return result(true, "Revision restored as draft.", { lockVersion: saved.lock_version, updatedAt: saved.updated_at }); }
