"use client";

import { useMemo, useState } from "react";
import { Copy, Upload } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Asset = { id: string; bucket: string; storage_path: string; original_name: string; mime_type: string; byte_size: number; alt_text: string; caption: string | null; status: "processing" | "ready" | "archived"; created_at: string };
const allowed = new Set(["image/jpeg", "image/png", "image/webp", "image/avif"]);

export function MediaLibrary({ initialAssets, userId, canUpload, canEdit }: { initialAssets: Asset[]; userId: string; canUpload: boolean; canEdit: boolean }) {
  const [assets, setAssets] = useState(initialAssets); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const visible = useMemo(() => assets.filter((asset) => `${asset.original_name} ${asset.alt_text} ${asset.storage_path}`.toLowerCase().includes(query.toLowerCase())), [assets, query]);
  const upload = async (file: File | null) => { if (!file || !canUpload) return; if (!allowed.has(file.type) || file.size > 15 * 1024 * 1024) { setNotice("Use JPG, PNG, WebP, or AVIF up to 15 MB."); return; } setBusy(true); setNotice(""); try { const supabase = createSupabaseBrowserClient(); const checksum = await hashFile(file); const extension = file.name.split(".").pop()?.toLowerCase() || "image"; const path = `uploads/${userId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from("site-media").upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) throw uploadError; const dimensions = await getDimensions(file); const { data, error } = await supabase.from("media_assets").insert({ bucket: "site-media", storage_path: path, original_name: file.name, mime_type: file.type, byte_size: file.size, width: dimensions.width, height: dimensions.height, checksum, alt_text: "", status: "ready", uploaded_by: userId }).select("id,bucket,storage_path,original_name,mime_type,byte_size,alt_text,caption,status,created_at").single(); if (error) { await supabase.storage.from("site-media").remove([path]); throw error; } setAssets((current) => [data, ...current]); setNotice("Image uploaded. Add alt text before using it publicly."); } catch (error) { setNotice(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } };
  const update = async (asset: Asset, alt: string, caption: string) => { if (!canEdit) return; const supabase = createSupabaseBrowserClient(); const { error } = await supabase.from("media_assets").update({ alt_text: alt, caption: caption || null }).eq("id", asset.id); if (error) { setNotice(error.message); return; } setAssets((current) => current.map((item) => item.id === asset.id ? { ...item, alt_text: alt, caption: caption || null } : item)); setNotice("Media details saved."); };
  const copy = async (asset: Asset) => { const supabase = createSupabaseBrowserClient(); const { data } = supabase.storage.from(asset.bucket).getPublicUrl(asset.storage_path); await navigator.clipboard.writeText(data.publicUrl); setNotice("Public URL copied."); };
  const archive = async (asset: Asset) => { if (!canEdit) return; if (!window.confirm(`Archive "${asset.original_name}"? It will be hidden from the library but not deleted from storage, and can be restored from the database if needed.`)) return; const supabase = createSupabaseBrowserClient(); const { error } = await supabase.from("media_assets").update({ status: "archived" }).eq("id", asset.id); if (error) { setNotice(error.message); return; } setAssets((current) => current.filter((item) => item.id !== asset.id)); setNotice("Image archived."); };
  return <div className="space-y-5"><section className="rounded-[1.5rem] border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#157670]">Supabase Storage</p><h2 className="mt-1 text-2xl font-bold">Media Library</h2></div>{canUpload && <label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#157670] px-4 py-2 text-xs font-bold text-white"><Upload className="h-4 w-4" />{busy ? "Uploading…" : "Upload image"}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={(event) => upload(event.target.files?.[0] ?? null)} className="sr-only" /></label>}</div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search media…" className="mt-5 h-10 w-full max-w-md rounded-xl border px-3 text-sm" />{notice && <p role="status" className="mt-3 rounded-xl bg-slate-50 p-3 text-xs">{notice}</p>}</section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map((asset) => <MediaCard key={asset.id} asset={asset} canEdit={canEdit} onCopy={() => copy(asset)} onSave={update} onArchive={() => archive(asset)} />)}{!visible.length && <p className="rounded-xl border bg-white p-8 text-center text-sm text-slate-500">No media found.</p>}</section></div>;
}
function MediaCard({ asset, canEdit, onCopy, onSave, onArchive }: { asset: Asset; canEdit: boolean; onCopy: () => void; onSave: (asset: Asset, alt: string, caption: string) => void; onArchive: () => void }) { const supabase = createSupabaseBrowserClient(); const { data } = supabase.storage.from(asset.bucket).getPublicUrl(asset.storage_path); const [alt, setAlt] = useState(asset.alt_text); const [caption, setCaption] = useState(asset.caption ?? ""); return <article className="overflow-hidden rounded-[1.5rem] border bg-white shadow-sm"><div className="aspect-video bg-slate-100 bg-cover bg-center" style={{ backgroundImage: `url("${data.publicUrl.replaceAll('"', "%22")}")` }} /><div className="space-y-3 p-4"><p className="truncate text-sm font-bold">{asset.original_name}</p><p className="text-[11px] text-slate-500">{Math.ceil(asset.byte_size / 1024)} KB · {asset.mime_type}</p><label className="block text-xs font-bold">Alt text<input disabled={!canEdit} value={alt} onChange={(event) => setAlt(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-2 text-sm font-normal" /></label><label className="block text-xs font-bold">Caption<input disabled={!canEdit} value={caption} onChange={(event) => setCaption(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-2 text-sm font-normal" /></label><div className="flex flex-wrap gap-2"><button type="button" onClick={onCopy} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><Copy className="h-3 w-3" />Copy URL</button>{canEdit && <button type="button" onClick={() => onSave(asset, alt, caption)} className="rounded-lg border px-3 py-2 text-xs font-bold">Save</button>}{canEdit && <button type="button" onClick={onArchive} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Archive</button>}</div></div></article>; }
async function hashFile(file: File) { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return [...new Uint8Array(digest)].map((value) => value.toString(16).padStart(2, "0")).join(""); }
async function getDimensions(file: File) { const url = URL.createObjectURL(file); try { const image = new Image(); await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("Unable to read image dimensions.")); image.src = url; }); return { width: image.naturalWidth || null, height: image.naturalHeight || null }; } finally { URL.revokeObjectURL(url); } }
