"use client";

import { useState, useTransition } from "react";
import { publishWebsiteSettings, saveWebsiteSettings } from "@/app/dashboard/settings/actions";

export type WebsiteSettings = { companyName: string; phone: string; email: string; address: string; instagram: string; facebook: string; defaultSeoTitle: string; defaultSeoDescription: string };

export function SettingsEditor({ initial, canEdit, canPublish }: { initial: WebsiteSettings; canEdit: boolean; canPublish: boolean }) {
  const [values, setValues] = useState(initial); const [notice, setNotice] = useState(""); const [pending, startTransition] = useTransition();
  const set = (key: keyof WebsiteSettings, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const save = () => startTransition(async () => { const result = await saveWebsiteSettings(values); setNotice(result.message); });
  const publish = () => startTransition(async () => { const result = await publishWebsiteSettings(); setNotice(result.message); });
  return <section className="rounded-[1.5rem] border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#157670]">Global website content</p><h2 className="mt-1 text-2xl font-bold">Website settings</h2><p className="mt-1 text-sm text-slate-500">Changes stay in Draft until they are published.</p></div><div className="flex gap-2">{canEdit && <button type="button" disabled={pending} onClick={save} className="rounded-xl border px-4 py-2 text-xs font-bold">Save draft</button>}{canPublish && <button type="button" disabled={pending} onClick={publish} className="rounded-xl bg-[#157670] px-4 py-2 text-xs font-bold text-white">Publish</button>}</div></div>{notice && <p role="status" className="mt-4 rounded-xl bg-slate-50 p-3 text-xs">{notice}</p>}<fieldset disabled={!canEdit || pending} className="mt-5 grid gap-4 md:grid-cols-2"><Input label="Company name" value={values.companyName} onChange={(value) => set("companyName", value)} /><Input label="Phone" value={values.phone} onChange={(value) => set("phone", value)} /><Input label="Email" type="email" value={values.email} onChange={(value) => set("email", value)} /><Input label="Instagram URL" value={values.instagram} onChange={(value) => set("instagram", value)} /><Input label="Facebook URL" value={values.facebook} onChange={(value) => set("facebook", value)} /><Input label="Default SEO title" value={values.defaultSeoTitle} onChange={(value) => set("defaultSeoTitle", value)} /><Area label="Address" value={values.address} onChange={(value) => set("address", value)} /><Area label="Default SEO description" value={values.defaultSeoDescription} onChange={(value) => set("defaultSeoDescription", value)} /></fieldset></section>;
}
function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="text-xs font-bold">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-xl border px-3 text-sm font-normal" /></label>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-bold">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} rows={3} className="mt-2 w-full rounded-xl border px-3 py-2 text-sm font-normal" /></label>; }
