-- Every card on the 5 /hospitality/* deep-dive pages becomes a real,
-- dashboard-editable hospitality entry tagged with showcaseRegion (which
-- page it appears on), showcaseIcon (its card icon), and displayOrder
-- (its position). All copy below is copied verbatim from what was already
-- hardcoded in each page's own source file — nothing fabricated.
--
-- Six of these slugs were archived in the previous migration as redundant
-- duplicates of the /cruises collection; that conclusion missed that the
-- /hospitality/nile-cruises showcase page reads these exact hospitality-type
-- slugs. Restore them (their draft_data was never touched by the archive)
-- and tag them for their real purpose here.

update public.content_entries
set status = 'published', archived_at = null
where content_type = 'hospitality'
  and slug in ('lady-carol', 'lady-mary', 'magic-ii', 'nile-divine', 'nile-excellence', 'nile-majestic');

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Building2", "displayOrder": 10, "sortOrder": 10}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/true-beach.jpg", "alt": "True Beach Resort", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Building2", "displayOrder": 10, "sortOrder": 10}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/true-beach.jpg", "alt": "True Beach Resort", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 10
where content_type = 'hospitality' and slug = 'true-beach-resort';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Ship", "displayOrder": 20, "sortOrder": 20}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/flash-boats.jpg", "alt": "Flash Yachting (Flash 3, 4, 5)", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Ship", "displayOrder": 20, "sortOrder": 20}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/flash-boats.jpg", "alt": "Flash Yachting (Flash 3, 4, 5)", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 20
where content_type = 'hospitality' and slug = 'flash-boats';

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'exquisite-private-beaches', 'Exquisite Private Beaches', 'en', 'published', 30, true, '{"title": "Exquisite Private Beaches", "name": "Exquisite Private Beaches", "slug": "exquisite-private-beaches", "shortDescription": "Unwind on golden sands merging seamlessly with the deep blue. Our private beaches offer unmatched tranquility, luxury cabanas, and elite beachside service for the most discerning guests.", "summary": "Unwind on golden sands merging seamlessly with the deep blue. Our private beaches offer unmatched tranquility, luxury cabanas, and elite beachside service for the most discerning guests.", "fullDescription": "Unwind on golden sands merging seamlessly with the deep blue. Our private beaches offer unmatched tranquility, luxury cabanas, and elite beachside service for the most discerning guests.", "country": "Egypt", "region": null, "location": "Marsa Alam", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Luxury Cabanas", "Beachside Dining", "Exclusive Access", "Crystal Clear Waters"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/true-beach-card.jpg", "alt": "Exquisite Private Beaches", "caption": ""}], "displayOrder": 30, "sortOrder": 30, "isActive": true, "showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Sun", "kind": "hospitality"}'::jsonb, '{"title": "Exquisite Private Beaches", "name": "Exquisite Private Beaches", "slug": "exquisite-private-beaches", "shortDescription": "Unwind on golden sands merging seamlessly with the deep blue. Our private beaches offer unmatched tranquility, luxury cabanas, and elite beachside service for the most discerning guests.", "summary": "Unwind on golden sands merging seamlessly with the deep blue. Our private beaches offer unmatched tranquility, luxury cabanas, and elite beachside service for the most discerning guests.", "fullDescription": "Unwind on golden sands merging seamlessly with the deep blue. Our private beaches offer unmatched tranquility, luxury cabanas, and elite beachside service for the most discerning guests.", "country": "Egypt", "region": null, "location": "Marsa Alam", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Luxury Cabanas", "Beachside Dining", "Exclusive Access", "Crystal Clear Waters"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/true-beach-card.jpg", "alt": "Exquisite Private Beaches", "caption": ""}], "displayOrder": 30, "sortOrder": 30, "isActive": true, "showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Sun", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'exquisite-private-beaches');

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'world-class-spa-kitesurfing-hub', 'World-Class Spa & Kitesurfing Hub', 'en', 'published', 40, true, '{"title": "World-Class Spa & Kitesurfing Hub", "name": "World-Class Spa & Kitesurfing Hub", "slug": "world-class-spa-kitesurfing-hub", "shortDescription": "Balance ultimate relaxation with thrilling adventure. Rejuvenate your senses at our holistic world-class spa, or ride the wind at our professional Tulipe Kitesurfing Hub.", "summary": "Balance ultimate relaxation with thrilling adventure. Rejuvenate your senses at our holistic world-class spa, or ride the wind at our professional Tulipe Kitesurfing Hub.", "fullDescription": "Balance ultimate relaxation with thrilling adventure. Rejuvenate your senses at our holistic world-class spa, or ride the wind at our professional Tulipe Kitesurfing Hub.", "country": "Egypt", "region": null, "location": "Marsa Alam", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Holistic Spa Treatments", "Professional Kitesurfing", "Wellness Therapies", "Extreme Sports"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/kitesurf.jpg", "alt": "World-Class Spa & Kitesurfing Hub", "caption": ""}], "displayOrder": 40, "sortOrder": 40, "isActive": true, "showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Wind", "kind": "hospitality"}'::jsonb, '{"title": "World-Class Spa & Kitesurfing Hub", "name": "World-Class Spa & Kitesurfing Hub", "slug": "world-class-spa-kitesurfing-hub", "shortDescription": "Balance ultimate relaxation with thrilling adventure. Rejuvenate your senses at our holistic world-class spa, or ride the wind at our professional Tulipe Kitesurfing Hub.", "summary": "Balance ultimate relaxation with thrilling adventure. Rejuvenate your senses at our holistic world-class spa, or ride the wind at our professional Tulipe Kitesurfing Hub.", "fullDescription": "Balance ultimate relaxation with thrilling adventure. Rejuvenate your senses at our holistic world-class spa, or ride the wind at our professional Tulipe Kitesurfing Hub.", "country": "Egypt", "region": null, "location": "Marsa Alam", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Holistic Spa Treatments", "Professional Kitesurfing", "Wellness Therapies", "Extreme Sports"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/kitesurf.jpg", "alt": "World-Class Spa & Kitesurfing Hub", "caption": ""}], "displayOrder": 40, "sortOrder": 40, "isActive": true, "showcaseRegion": "coastal-sanctuaries", "showcaseIcon": "Wind", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'world-class-spa-kitesurfing-hub');

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "tropical-retreats", "showcaseIcon": "Building2", "displayOrder": 10, "sortOrder": 10}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/zanzibar-island.jpg", "alt": "Kiwengwa Beach Resort", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "tropical-retreats", "showcaseIcon": "Building2", "displayOrder": 10, "sortOrder": 10}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/zanzibar-island.jpg", "alt": "Kiwengwa Beach Resort", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 10
where content_type = 'hospitality' and slug = 'kiwengwa-beach-resort';

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'exclusive-white-sand-beaches', 'Exclusive White Sand Beaches', 'en', 'published', 20, true, '{"title": "Exclusive White Sand Beaches", "name": "Exclusive White Sand Beaches", "slug": "exclusive-white-sand-beaches", "shortDescription": "Relax and unwind on some of the most famous beaches in Africa. We organize private boat safaris to secluded sandbanks in the middle of the ocean, offering absolute tranquility under the tropical sun.", "summary": "Relax and unwind on some of the most famous beaches in Africa. We organize private boat safaris to secluded sandbanks in the middle of the ocean, offering absolute tranquility under the tropical sun.", "fullDescription": "Relax and unwind on some of the most famous beaches in Africa. We organize private boat safaris to secluded sandbanks in the middle of the ocean, offering absolute tranquility under the tropical sun.", "country": "Tanzania", "region": null, "location": "Zanzibar", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Private Sandbanks", "Crystal Clear Waters", "Luxury Sunbeds", "Bespoke Beachside Service"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/zanzibar-resort.jpg", "alt": "Exclusive White Sand Beaches", "caption": ""}], "displayOrder": 20, "sortOrder": 20, "isActive": true, "showcaseRegion": "tropical-retreats", "showcaseIcon": "Sun", "kind": "hospitality"}'::jsonb, '{"title": "Exclusive White Sand Beaches", "name": "Exclusive White Sand Beaches", "slug": "exclusive-white-sand-beaches", "shortDescription": "Relax and unwind on some of the most famous beaches in Africa. We organize private boat safaris to secluded sandbanks in the middle of the ocean, offering absolute tranquility under the tropical sun.", "summary": "Relax and unwind on some of the most famous beaches in Africa. We organize private boat safaris to secluded sandbanks in the middle of the ocean, offering absolute tranquility under the tropical sun.", "fullDescription": "Relax and unwind on some of the most famous beaches in Africa. We organize private boat safaris to secluded sandbanks in the middle of the ocean, offering absolute tranquility under the tropical sun.", "country": "Tanzania", "region": null, "location": "Zanzibar", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Private Sandbanks", "Crystal Clear Waters", "Luxury Sunbeds", "Bespoke Beachside Service"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/zanzibar-resort.jpg", "alt": "Exclusive White Sand Beaches", "caption": ""}], "displayOrder": 20, "sortOrder": 20, "isActive": true, "showcaseRegion": "tropical-retreats", "showcaseIcon": "Sun", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'exclusive-white-sand-beaches');

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'premium-safari-integrations', 'Premium Safari Integrations', 'en', 'published', 30, true, '{"title": "Premium Safari Integrations", "name": "Premium Safari Integrations", "slug": "premium-safari-integrations", "shortDescription": "Experience the best of both worlds. Seamlessly combine your beach retreat with thrilling wildlife excursions in the majestic Savannas, including over-day trips to Mikumi or Selous reserves.", "summary": "Experience the best of both worlds. Seamlessly combine your beach retreat with thrilling wildlife excursions in the majestic Savannas, including over-day trips to Mikumi or Selous reserves.", "fullDescription": "Experience the best of both worlds. Seamlessly combine your beach retreat with thrilling wildlife excursions in the majestic Savannas, including over-day trips to Mikumi or Selous reserves.", "country": "Tanzania", "region": null, "location": "Zanzibar", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Private Car Safaris", "Mikumi & Selous Tours", "Guided Forest Walks", "Spice Tour Experiences"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/safari-main.jpg", "alt": "Premium Safari Integrations", "caption": ""}], "displayOrder": 30, "sortOrder": 30, "isActive": true, "showcaseRegion": "tropical-retreats", "showcaseIcon": "Trees", "kind": "hospitality"}'::jsonb, '{"title": "Premium Safari Integrations", "name": "Premium Safari Integrations", "slug": "premium-safari-integrations", "shortDescription": "Experience the best of both worlds. Seamlessly combine your beach retreat with thrilling wildlife excursions in the majestic Savannas, including over-day trips to Mikumi or Selous reserves.", "summary": "Experience the best of both worlds. Seamlessly combine your beach retreat with thrilling wildlife excursions in the majestic Savannas, including over-day trips to Mikumi or Selous reserves.", "fullDescription": "Experience the best of both worlds. Seamlessly combine your beach retreat with thrilling wildlife excursions in the majestic Savannas, including over-day trips to Mikumi or Selous reserves.", "country": "Tanzania", "region": null, "location": "Zanzibar", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Private Car Safaris", "Mikumi & Selous Tours", "Guided Forest Walks", "Spice Tour Experiences"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/safari-main.jpg", "alt": "Premium Safari Integrations", "caption": ""}], "displayOrder": 30, "sortOrder": 30, "isActive": true, "showcaseRegion": "tropical-retreats", "showcaseIcon": "Trees", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'premium-safari-integrations');

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'tropical-corporate-retreats', 'Tropical Corporate Retreats', 'en', 'published', 40, true, '{"title": "Tropical Corporate Retreats", "name": "Tropical Corporate Retreats", "slug": "tropical-corporate-retreats", "shortDescription": "Elevate your corporate events in a breathtaking tropical setting. We offer tailored B2B solutions for incentive groups, combining professional environments with unforgettable leisure activities and VI", "summary": "Elevate your corporate events in a breathtaking tropical setting. We offer tailored B2B solutions for incentive groups, combining professional environments with unforgettable leisure activities and VI", "fullDescription": "Elevate your corporate events in a breathtaking tropical setting. We offer tailored B2B solutions for incentive groups, combining professional environments with unforgettable leisure activities and VIP mobility.", "country": "Tanzania", "region": null, "location": "Zanzibar", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Tailored B2B Solutions", "Incentive Travel", "Team Building Events", "VIP Ground Mobility"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/service-mice.jpg", "alt": "Tropical Corporate Retreats", "caption": ""}], "displayOrder": 40, "sortOrder": 40, "isActive": true, "showcaseRegion": "tropical-retreats", "showcaseIcon": "Briefcase", "kind": "hospitality"}'::jsonb, '{"title": "Tropical Corporate Retreats", "name": "Tropical Corporate Retreats", "slug": "tropical-corporate-retreats", "shortDescription": "Elevate your corporate events in a breathtaking tropical setting. We offer tailored B2B solutions for incentive groups, combining professional environments with unforgettable leisure activities and VI", "summary": "Elevate your corporate events in a breathtaking tropical setting. We offer tailored B2B solutions for incentive groups, combining professional environments with unforgettable leisure activities and VI", "fullDescription": "Elevate your corporate events in a breathtaking tropical setting. We offer tailored B2B solutions for incentive groups, combining professional environments with unforgettable leisure activities and VIP mobility.", "country": "Tanzania", "region": null, "location": "Zanzibar", "categoryId": "66131601-edec-4d02-a845-0c506663545d", "roomsOrCabins": null, "facilities": ["Tailored B2B Solutions", "Incentive Travel", "Team Building Events", "VIP Ground Mobility"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/service-mice.jpg", "alt": "Tropical Corporate Retreats", "caption": ""}], "displayOrder": 40, "sortOrder": 40, "isActive": true, "showcaseRegion": "tropical-retreats", "showcaseIcon": "Briefcase", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'tropical-corporate-retreats');

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Building2", "displayOrder": 10, "sortOrder": 10}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/sicily-main.jpg", "alt": "President Sea Palace Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Building2", "displayOrder": 10, "sortOrder": 10}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/sicily-main.jpg", "alt": "President Sea Palace Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 10
where content_type = 'hospitality' and slug = 'president-sea-palace-hotel';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "MapPin", "displayOrder": 20, "sortOrder": 20}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/sardinia-main.jpg", "alt": "Castelsardo Resort", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "MapPin", "displayOrder": 20, "sortOrder": 20}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/sardinia-main.jpg", "alt": "Castelsardo Resort", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 20
where content_type = 'hospitality' and slug = 'castelsardo-resort';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Wine", "displayOrder": 30, "sortOrder": 30}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/italy-resorts.jpg", "alt": "Hopps Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Wine", "displayOrder": 30, "sortOrder": 30}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/italy-resorts.jpg", "alt": "Hopps Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 30
where content_type = 'hospitality' and slug = 'hopps-hotel';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Building2", "displayOrder": 40, "sortOrder": 40}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-italy.jpg", "alt": "Baia D''Oro Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Building2", "displayOrder": 40, "sortOrder": 40}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-italy.jpg", "alt": "Baia D''Oro Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 40
where content_type = 'hospitality' and slug = 'baia-doro-hotel';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "MapPin", "displayOrder": 50, "sortOrder": 50}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/sicily-main.jpg", "alt": "Hotel Eloro", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "MapPin", "displayOrder": 50, "sortOrder": 50}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/sicily-main.jpg", "alt": "Hotel Eloro", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 50
where content_type = 'hospitality' and slug = 'hotel-club-eloro';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Briefcase", "displayOrder": 60, "sortOrder": 60}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/italy-resorts.jpg", "alt": "Hotel Dolcestate Club", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Briefcase", "displayOrder": 60, "sortOrder": 60}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/italy-resorts.jpg", "alt": "Hotel Dolcestate Club", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 60
where content_type = 'hospitality' and slug = 'hotel-dolcestate-club';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Wine", "displayOrder": 70, "sortOrder": 70}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-italy.jpg", "alt": "Le Dune Beach Club", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "european-elegance", "showcaseIcon": "Wine", "displayOrder": 70, "sortOrder": 70}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-italy.jpg", "alt": "Le Dune Beach Club", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 70
where content_type = 'hospitality' and slug = 'le-dune-beach-club';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "urban-centers", "showcaseIcon": "Landmark", "displayOrder": 10, "sortOrder": 10}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/1920s-hotel.jpg", "alt": "1920s Boutique Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "urban-centers", "showcaseIcon": "Landmark", "displayOrder": 10, "sortOrder": 10}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/1920s-hotel.jpg", "alt": "1920s Boutique Hotel", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 10
where content_type = 'hospitality' and slug = '1920s-boutique-hotel';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "urban-centers", "showcaseIcon": "UtensilsCrossed", "displayOrder": 20, "sortOrder": 20}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/carlos.jpg", "alt": "Carlo''s Restaurant", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "urban-centers", "showcaseIcon": "UtensilsCrossed", "displayOrder": 20, "sortOrder": 20}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/carlos.jpg", "alt": "Carlo''s Restaurant", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 20
where content_type = 'hospitality' and slug = 'carlo-heliopolis';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "urban-centers", "showcaseIcon": "Wine", "displayOrder": 30, "sortOrder": 30}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/rossini.jpg", "alt": "Rossini Fine Dining", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "urban-centers", "showcaseIcon": "Wine", "displayOrder": 30, "sortOrder": 30}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/rossini.jpg", "alt": "Rossini Fine Dining", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 30
where content_type = 'hospitality' and slug = 'rossini';

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'personalized-vip-concierge', 'Personalized VIP Concierge', 'en', 'published', 40, true, '{"title": "Personalized VIP Concierge", "name": "Personalized VIP Concierge", "slug": "personalized-vip-concierge", "shortDescription": "Our urban hospitality is defined by absolute attention to detail. From securing exclusive dining reservations to arranging private chauffeured city tours, our dedicated VIP concierge ensures a flawles", "summary": "Our urban hospitality is defined by absolute attention to detail. From securing exclusive dining reservations to arranging private chauffeured city tours, our dedicated VIP concierge ensures a flawles", "fullDescription": "Our urban hospitality is defined by absolute attention to detail. From securing exclusive dining reservations to arranging private chauffeured city tours, our dedicated VIP concierge ensures a flawless, highly personalized Cairo experience.", "country": "Egypt", "region": null, "location": "Cairo", "categoryId": "b1390cc2-20a0-452b-9dcf-432bef38e244", "roomsOrCabins": null, "facilities": ["24/7 VIP Assistance", "Private City Tours", "Exclusive Reservations", "Chauffeur Services"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/office-1.jpg", "alt": "Personalized VIP Concierge", "caption": ""}], "displayOrder": 40, "sortOrder": 40, "isActive": true, "showcaseRegion": "urban-centers", "showcaseIcon": "Crown", "kind": "hospitality"}'::jsonb, '{"title": "Personalized VIP Concierge", "name": "Personalized VIP Concierge", "slug": "personalized-vip-concierge", "shortDescription": "Our urban hospitality is defined by absolute attention to detail. From securing exclusive dining reservations to arranging private chauffeured city tours, our dedicated VIP concierge ensures a flawles", "summary": "Our urban hospitality is defined by absolute attention to detail. From securing exclusive dining reservations to arranging private chauffeured city tours, our dedicated VIP concierge ensures a flawles", "fullDescription": "Our urban hospitality is defined by absolute attention to detail. From securing exclusive dining reservations to arranging private chauffeured city tours, our dedicated VIP concierge ensures a flawless, highly personalized Cairo experience.", "country": "Egypt", "region": null, "location": "Cairo", "categoryId": "b1390cc2-20a0-452b-9dcf-432bef38e244", "roomsOrCabins": null, "facilities": ["24/7 VIP Assistance", "Private City Tours", "Exclusive Reservations", "Chauffeur Services"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/office-1.jpg", "alt": "Personalized VIP Concierge", "caption": ""}], "displayOrder": 40, "sortOrder": 40, "isActive": true, "showcaseRegion": "urban-centers", "showcaseIcon": "Crown", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'personalized-vip-concierge');

insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'nile-serenity', 'Nile Serenity', 'en', 'published', 10, true, '{"title": "Nile Serenity", "name": "Nile Serenity", "slug": "nile-serenity", "shortDescription": "Setting the absolute benchmark for river cruising. Designed for the global elite, offering uninterrupted panoramic views and uncompromised luxury.", "summary": "Setting the absolute benchmark for river cruising. Designed for the global elite, offering uninterrupted panoramic views and uncompromised luxury.", "fullDescription": "Setting the absolute benchmark for river cruising. Designed for the global elite, offering uninterrupted panoramic views and uncompromised luxury.", "country": "Egypt", "region": null, "location": "Luxor and Aswan", "categoryId": "66fae32c-ee8d-4b59-a382-39371c7696db", "roomsOrCabins": 72, "facilities": ["72 Luxury Suites", "Gourmet Gastronomy", "Rooftop Infinity Pool", "Private Docking"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/cruise-1.jpg", "alt": "Nile Serenity", "caption": ""}], "displayOrder": 10, "sortOrder": 10, "isActive": true, "showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "kind": "hospitality"}'::jsonb, '{"title": "Nile Serenity", "name": "Nile Serenity", "slug": "nile-serenity", "shortDescription": "Setting the absolute benchmark for river cruising. Designed for the global elite, offering uninterrupted panoramic views and uncompromised luxury.", "summary": "Setting the absolute benchmark for river cruising. Designed for the global elite, offering uninterrupted panoramic views and uncompromised luxury.", "fullDescription": "Setting the absolute benchmark for river cruising. Designed for the global elite, offering uninterrupted panoramic views and uncompromised luxury.", "country": "Egypt", "region": null, "location": "Luxor and Aswan", "categoryId": "66fae32c-ee8d-4b59-a382-39371c7696db", "roomsOrCabins": 72, "facilities": ["72 Luxury Suites", "Gourmet Gastronomy", "Rooftop Infinity Pool", "Private Docking"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/cruise-1.jpg", "alt": "Nile Serenity", "caption": ""}], "displayOrder": 10, "sortOrder": 10, "isActive": true, "showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'nile-serenity');

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 20, "sortOrder": 20}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-2.jpg", "alt": "Nile Excellence", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 20, "sortOrder": 20}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-2.jpg", "alt": "Nile Excellence", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 20
where content_type = 'hospitality' and slug = 'nile-excellence';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 30, "sortOrder": 30}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-3.jpg", "alt": "Lady Carol", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 30, "sortOrder": 30}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-3.jpg", "alt": "Lady Carol", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 30
where content_type = 'hospitality' and slug = 'lady-carol';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 40, "sortOrder": 40}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-4.jpg", "alt": "Magic II", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 40, "sortOrder": 40}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-4.jpg", "alt": "Magic II", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 40
where content_type = 'hospitality' and slug = 'magic-ii';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 50, "sortOrder": 50}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-5.jpg", "alt": "Magic I", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 50, "sortOrder": 50}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-5.jpg", "alt": "Magic I", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 50
where content_type = 'hospitality' and slug = 'magic-i';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 60, "sortOrder": 60}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-6.jpg", "alt": "Lady Mary", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 60, "sortOrder": 60}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/cruise-6.jpg", "alt": "Lady Mary", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 60
where content_type = 'hospitality' and slug = 'lady-mary';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 70, "sortOrder": 70}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-cruise.jpg", "alt": "Nile Majestic", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 70, "sortOrder": 70}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-cruise.jpg", "alt": "Nile Majestic", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 70
where content_type = 'hospitality' and slug = 'nile-majestic';

update public.content_entries
set draft_data = (draft_data || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 80, "sortOrder": 80}'::jsonb) || case when jsonb_array_length(coalesce(draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-cruise.jpg", "alt": "Nile Divine", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    published_data = coalesce(published_data, draft_data) || '{"showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "displayOrder": 80, "sortOrder": 80}'::jsonb || case when jsonb_array_length(coalesce(published_data->'gallery', draft_data->'gallery', '[]'::jsonb)) = 0 then jsonb_build_object('gallery', '[{"assetId": null, "url": "/images/hospitality-cruise.jpg", "alt": "Nile Divine", "caption": ""}]'::jsonb) else '{}'::jsonb end,
    sort_order = 80
where content_type = 'hospitality' and slug = 'nile-divine';

