-- Four approved Home Hero slides. Draft-only; the existing published hero is not changed.
update public.page_sections section
set draft_data = section.draft_data || jsonb_build_object('slides', jsonb_build_array(
  jsonb_build_object('id','group','name','Flash Group','eyebrow','A 40-Year Hospitality Legacy','title','Crafting Hospitality Since 1985','subtitle','An Egyptian-born tourism and hospitality group owning Nile cruises, resorts, restaurants, yachts, and premium mobility assets across strategic destinations.','primaryCta',jsonb_build_object('label','Partner With Flash Group','href','/contact'),'secondaryCta',jsonb_build_object('label','Explore Portfolio','href','/brands'),'image',jsonb_build_object('assetId',null,'url','/images/egypt-bg.jpg','alt','Flash Group'),'enabled',true),
  jsonb_build_object('id','cruises','name','Cruises','eyebrow','Owned Nile Cruise Fleet','title','Luxury Journeys on the Nile','subtitle','A curated fleet of Nile vessels delivering controlled quality, seamless logistics, and unforgettable river experiences for global partners.','primaryCta',jsonb_build_object('label','Discover Cruises','href','/cruises'),'secondaryCta',jsonb_build_object('label','Contact us','href','/contact'),'image',jsonb_build_object('assetId',null,'url','/images/hospitality-cruise.jpg','alt','Luxury Nile cruise'),'enabled',true),
  jsonb_build_object('id','hospitality','name','Hospitality','eyebrow','Hotels, Resorts & Fine Dining','title','Assets That Shape the Experience','subtitle','From Red Sea sanctuaries and boutique heritage hotels to international resorts and restaurants, Flash Group owns the journey end-to-end.','primaryCta',jsonb_build_object('label','Explore Hospitality','href','/hospitality'),'secondaryCta',jsonb_build_object('label','Contact us','href','/contact'),'image',jsonb_build_object('assetId',null,'url','/images/zanzibar-bg.jpg','alt','Flash Group hospitality'),'enabled',true),
  jsonb_build_object('id','mobility','name','Mobility','eyebrow','Executive Transport Infrastructure','title','Precision on Every Route','subtitle','A premium fleet, trained chauffeurs, and operational control built for B2B travel, MICE, VIP transfers, and large-scale movements.','primaryCta',jsonb_build_object('label','Our services','href','/services'),'secondaryCta',jsonb_build_object('label','Contact us','href','/contact'),'image',jsonb_build_object('assetId',null,'url','/images/fleet-showcase.jpg','alt','Flash Group executive mobility'),'enabled',true)
))
from public.pages page
where section.page_id = page.id and page.key = 'home' and page.locale = 'en' and section.key = 'hero'
  and coalesce(jsonb_array_length(section.draft_data->'slides'), 0) <> 4;
