-- On production, no content_entries row of content_type='hospitality' with
-- slug='magic-i' ever existed (only a 'cruise'-type twin does) — unlike the
-- local seed data, which happens to already have one. The previous migration's
-- UPDATE-only handling for magic-i silently matched zero rows there, leaving
-- the nile-cruises showcase page's "Magic I" card without any dashboard-
-- editable backing. Insert one now, using the same real copy already in
-- src/app/hospitality/nile-cruises/page.tsx. Safe to run on any environment:
-- the guard skips it wherever a hospitality-type magic-i row already exists
-- (e.g. local, already tagged by the previous migration).
insert into public.content_entries (content_type, slug, title, locale, status, sort_order, is_active, draft_data, published_data, published_at)
select 'hospitality', 'magic-i', 'Magic I', 'en', 'published', 50, true, '{"title": "Magic I", "name": "Magic I", "slug": "magic-i", "shortDescription": "A legacy of majestic sailings. The optimal choice for large corporate incentive groups seeking authentic Egyptian hospitality.", "summary": "A legacy of majestic sailings. The optimal choice for large corporate incentive groups seeking authentic Egyptian hospitality.", "fullDescription": "A legacy of majestic sailings. The optimal choice for large corporate incentive groups seeking authentic Egyptian hospitality.", "country": "Egypt", "region": null, "location": "Luxor and Aswan", "categoryId": "66fae32c-ee8d-4b59-a382-39371c7696db", "roomsOrCabins": 70, "facilities": ["70 Cabins", "Grand Restaurant", "Bazaar Onboard", "Guided Excursions"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/cruise-5.jpg", "alt": "Magic I", "caption": ""}], "displayOrder": 50, "sortOrder": 50, "isActive": true, "showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "kind": "hospitality"}'::jsonb, '{"title": "Magic I", "name": "Magic I", "slug": "magic-i", "shortDescription": "A legacy of majestic sailings. The optimal choice for large corporate incentive groups seeking authentic Egyptian hospitality.", "summary": "A legacy of majestic sailings. The optimal choice for large corporate incentive groups seeking authentic Egyptian hospitality.", "fullDescription": "A legacy of majestic sailings. The optimal choice for large corporate incentive groups seeking authentic Egyptian hospitality.", "country": "Egypt", "region": null, "location": "Luxor and Aswan", "categoryId": "66fae32c-ee8d-4b59-a382-39371c7696db", "roomsOrCabins": 70, "facilities": ["70 Cabins", "Grand Restaurant", "Bazaar Onboard", "Guided Excursions"], "diningOptions": [], "accessibility": [], "gallery": [{"assetId": null, "url": "/images/cruise-5.jpg", "alt": "Magic I", "caption": ""}], "displayOrder": 50, "sortOrder": 50, "isActive": true, "showcaseRegion": "nile-cruises", "showcaseIcon": "Ship", "kind": "hospitality"}'::jsonb, now()
where not exists (select 1 from public.content_entries where content_type = 'hospitality' and slug = 'magic-i');
